# Generated by Django 5.2.7 on 2025-10-20 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome da equipe')),
                ('cidade', models.CharField(blank=True, max_length=80, verbose_name='Cidade')),
                ('patrocinador', models.CharField(blank=True, max_length=120, verbose_name='Patrocinador')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Pista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome da pista')),
                ('cidade', models.CharField(max_length=80, verbose_name='Cidade')),
                ('extensao_km', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Extensão (km)')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=120, verbose_name='Modelo')),
                ('placa', models.CharField(max_length=10, unique=True, verbose_name='Placa')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano')),
                ('cor', models.CharField(blank=True, max_length=40, verbose_name='Cor')),
                ('equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carros', to='core.equipe')),
            ],
            options={
                'ordering': ['modelo', 'placa'],
            },
        ),
        migrations.CreateModel(
            name='Piloto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome do piloto')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de nascimento')),
                ('documento', models.CharField(blank=True, max_length=30, verbose_name='Documento')),
                ('categoria', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('PRO-AM', 'PRO-AM')], default='A', max_length=10, verbose_name='Categoria')),
                ('equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pilotos', to='core.equipe')),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Corrida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome da corrida')),
                ('data', models.DateField(verbose_name='Data')),
                ('status', models.CharField(choices=[('PLANEJADA', 'Planejada'), ('EM_ANDAMENTO', 'Em andamento'), ('ENCERRADA', 'Encerrada')], default='PLANEJADA', max_length=20, verbose_name='Status')),
                ('categoria', models.CharField(choices=[('STREET', 'Street'), ('DRAG', 'Drag'), ('DRIFT', 'Drift')], default='STREET', max_length=20, verbose_name='Categoria')),
                ('pista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corridas', to='core.pista')),
            ],
            options={
                'ordering': ['-data', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_largada', models.PositiveIntegerField(verbose_name='Número de largada')),
                ('situacao', models.CharField(choices=[('APROVADA', 'Aprovada'), ('PENDENTE', 'Pendente'), ('INDEFERIDA', 'Indeferida')], default='PENDENTE', max_length=10, verbose_name='Situação')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscricoes', to='core.carro')),
                ('corrida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='core.corrida')),
                ('piloto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscricoes', to='core.piloto')),
            ],
            options={
                'ordering': ['corrida', 'numero_largada'],
                'unique_together': {('corrida', 'numero_largada'), ('corrida', 'piloto')},
            },
        ),
    ]
